/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;


import Vista.MyCanvas;
import Control.Control;
import dao.Animal;
import dao.Zona;
import java.util.ArrayList;


/**
 *
 * @author usuario
 */
public class Ventana extends javax.swing.JFrame {

    Control c;
    

    /**
     * Creates new form NewJFrame
     */

    public Ventana() {
       
        ArrayList<String> zonas = new ArrayList<String>();
        c = new Control();
        zonas = c.getZonas();
        String[] zArray = new String[zonas.size()];
        //Conversion
        zonas.toArray(zArray);
        initComponents();
        opcionesZona.setModel(new javax.swing.DefaultComboBoxModel<>(zArray));
        actListaAnimales();
        this.setVisible(true);

    }

    private void actListaAnimales(){
        ArrayList<String> animales = new ArrayList(); 
        animales = c.getAnimales();
        String[] aArray = new String[animales.size()];
        animales.toArray(aArray);
        opcionesBorrar.setModel(new javax.swing.DefaultComboBoxModel<>(aArray));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
       
        jLabel2 = new javax.swing.JLabel();
        canvas1 = new MyCanvas();
        jLabel4 = new javax.swing.JLabel();
        txtNuevoAnimal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        opcionesZona = new javax.swing.JComboBox<>();
        BotonNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        labelPruebaBusqueda = new javax.swing.JLabel();
        txtInfoNuevoAnimal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        opcionesBorrar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        BotonEliminar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas1 = new MyCanvas();

        jLabel4.setText("Nombre:");

        jLabel1.setText("Zona:");
        BotonNuevo.setText("Introducir");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoAnimal(evt);
            }
        });

        jLabel5.setText("---------------------------------------------------------------------------------");

        jLabel6.setText("Buscar animal");

        jLabel7.setText("Nombre:");

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");
        
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarAnimalActionPerformed(evt);
            }
        });

        jLabel8.setText("---------------------------------------------------------------------------------");

       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNuevoAnimal)
                                    .addComponent(opcionesZona, 0, 125, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonNuevo))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opcionesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonEliminar))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(BotonBuscar))
                            .addComponent(labelPruebaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInfoNuevoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNuevoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(opcionesZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(BotonNuevo)))
                        .addGap(18, 18, 18)
                        .addComponent(txtInfoNuevoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(opcionesBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminar))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPruebaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Zona zona =c.getoZonaFromAnimal(this.txtBuscador.getText());
        if(zona !=null){
            canvas1.setCoordenadas(zona.getCoordenadaX(),zona.getCoordenadaY());
            this.labelPruebaBusqueda.setText("");
        }else{
            this.labelPruebaBusqueda.setText("Animal no registrado en la base de datos");
            canvas1.pintaMapa();
        }
        this.txtBuscador.setText("");
        canvas1.repaint();
    }
      private void BotonNuevoAnimal(java.awt.event.ActionEvent evt) {                                  
        String animal = this.txtNuevoAnimal.getText();
        if(!animal.isEmpty() ){
            txtInfoNuevoAnimal.setText("");
            String zonaSelected = (String)this.opcionesZona.getSelectedItem();
            Animal newAnimal = new Animal();
            newAnimal.setNombre(animal);
            Zona z = c.buscaZona(zonaSelected);
            if(z != null){
                newAnimal.setZonaidZona(z);
                if(c.anadirAnimal(newAnimal)){
                    this.txtNuevoAnimal.setText("");
                    txtInfoNuevoAnimal.setText("Animal correctamente introducido");
                    actListaAnimales();
                }else{
                    txtInfoNuevoAnimal.setText("Animal ya registrado en la base de datos");
                }
            }
        }else{
            txtInfoNuevoAnimal.setText("Introduzca un nombre");
        }   
    } 
      private void BorrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String nombreAnimal = (String)this.opcionesBorrar.getSelectedItem();
        if(c.borraAnimal(nombreAnimal)){
            actListaAnimales();
            System.out.println("Animal eliminado");
        }
        
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonNuevo;
    private MyCanvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelPruebaBusqueda;
    private javax.swing.JComboBox<String> opcionesBorrar;
    private javax.swing.JComboBox<String> opcionesZona;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JLabel txtInfoNuevoAnimal;
    private javax.swing.JTextField txtNuevoAnimal;
    // End of variables declaration                   
}
